{
 "title": "Novel Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "运行状态",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "crawler_status{job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "每分钟成功请求次",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(crawler_request_count{type=\"finished\", job=\"novel-server\", instance=\"novel-server::8233\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每分钟请求数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(crawler_request_count{type=\"finished\", job=\"novel-server\", instance=\"novel-server::8233\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(crawler_request_count{type=\"retries\", job=\"novel-server\", instance=\"novel-server::8233\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(crawler_request_count{type=\"failed\", job=\"novel-server\", instance=\"novel-server::8233\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均每分钟请求数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "crawler_request_count_pre_minute{type=\"finished\", job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "平均请求时间",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "crawler_request_avg_duration_ms{type=\"finished\", job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "crawler_request_avg_duration_ms{type=\"failed\", job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已完成请求",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "crawler_request_count{type=\"finished\", job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时状态",
   "type": "canvas",
   "gridPos": { "h": 6, "w": 8, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "crawler_status{job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "开始时间",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_start_at{job=\"novel-server\", instance=\"novel-server::8233\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "开始于",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crawler_start_at{job=\"novel-server\", instance=\"novel-server:8233\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}